using Comonicon
using Test
using Comonicon.PATH
using Comonicon.BuildTools: write_path, contain_comonicon_path, contain_comonicon_fpath

rcfile_content = """
some words
# generated by Comonicon
# Julia bin PATH
export PATH="/Users/roger/.julia/bin:\$PATH"\n
# generated by Comonicon
# Julia autocompletion PATH
export FPATH="/Users/roger/.julia/completions:\$FPATH"
"""

rcfile = tempname()
rm(rcfile, force=true)
write(rcfile, "some words")
write_path(rcfile, true, Dict())
@test strip(read(rcfile, String)) == strip(rcfile_content)
