name = "foo"

[install]
completion=true
quiet=false
compile="min"
optimize=2

[sysimg]
incremental=true
filter_stdlibs=false
cpu_target="native"

# [download]
# host="github.com"
# user="Roger-luo"
# repo="Foo.jl"
